export const GET_LOCATIONS = 'GET_LOCATIONS';
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_FAIL = 'GET_LOCATIONS_FAIL';

export const CREATE_LOCATION = 'CREATE_LOCATION';
export const CREATE_LOCATION_SUCCESS = 'CREATE_LOCATION_SUCCESS';
export const CREATE_LOCATION_FAIL = 'CREATE_LOCATION_FAIL';

export const UPDATE_LOCATION_FIELD = 'UPDATE_LOCATION_FIELD';
export const UPDATE_LOCATION_FIELD_SUCCESS = 'UPDATE_LOCATION_FIELD_SUCCESS';
export const UPDATE_LOCATION_FIELD_FAIL = 'UPDATE_LOCATION_FIELD_FAIL';

export const DELETE_LOCATION = 'DELETE_LOCATION';
export const DELETE_LOCATION_SUCCESS = 'DELETE_LOCATION_SUCCESS';
export const DELETE_LOCATION_FAIL = 'DELETE_LOCATION_FAIL';

export const INIT_LOCATIONS = 'INIT_LOCATIONS';

export const ACTIVATE_LOCATION_FIELD = 'ACTIVATE_LOCATION_FIELD';
