export const GET_LOCATION_STRUCTURE = 'GET_LOCATION_STRUCTURE';
export const GET_LOCATION_STRUCTURE_SUCCESS = 'GET_LOCATION_STRUCTURE_SUCCESS';
export const GET_LOCATION_STRUCTURE_FAIL = 'GET_LOCATION_STRUCTURE_FAIL';

export const UPDATE_LOCATION_STRUCTURE = 'UPDATE_LOCATION_STRUCTURE';
export const UPDATE_LOCATION_STRUCTURE_SUCCESS = 'UPDATE_LOCATION_STRUCTURE_SUCCESS';
export const UPDATE_LOCATION_STRUCTURE_FAIL = 'UPDATE_LOCATION_STRUCTURE_FAIL';

export const CHANGE_FIELD = 'CHANGE_FIELD';
export const ADD_FIELD = 'ADD_FIELD';
export const REMOVE_FIELD = 'REMOVE_FIELD';

export const INIT_LOCATION_STRUCTURE = 'INIT_LOCATION_STRUCTURE';


